# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       mosh

# >> macros
# << macros

Summary:    Mobile Shell
Version:    1.4.0
Release:    0
Group:      Applications
License:    GPLv3
URL:        https://mosh.org/
Source0:    %{name}-%{version}.tar.gz
Source1:    99-mosh-firewall.conf
Source100:  mosh.yaml
Source101:  mosh-rpmlintrc
Requires:   openssh-clients
Requires:   openssl
Requires:   perl(IO::Socket::IP)
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(ncursesw)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  protobuf-compiler
BuildRequires:  protobuf-devel
BuildRequires:  libutempter-devel

%description
Mosh is a remote terminal application that supports:
  - intermittent network connectivity,
  - roaming to different IP address without dropping the connection, and
  - intelligent local echo and line editing to reduce the effects
    of "network lag" on high-latency connections.

%if "%{?vendor}" == "chum"
Type: console-application
PackagedBy: nephros
Categories:
  - Shell
  - RemoteAccess
Custom:
  Repo: https://github.com/mobile-shell/mosh
  PackagingRepo: https://github.com/sailfishos-chum/mosh
PackageIcon: https://raw.githubusercontent.com/mobile-shell/mobile-shell.github.io/master/mosh-chrome.png
Screenshots:
  - https://raw.githubusercontent.com/mobile-shell/mobile-shell.github.io/master/mosh.png
%endif


%package server
Summary:    Mobile Shell Server
Group:      Applications

%description server
NOTE: This will install a firewall rule that allows incoming connections on wifii on ports 60001-60999!

Mosh is a remote terminal application that supports:
  - intermittent network connectivity,
  - roaming to different IP address without dropping the connection, and
  - intelligent local echo and line editing to reduce the effects
    of "network lag" on high-latency connections.

%if "%{?vendor}" == "chum"
Title: mosh Server
PackagedBy: nephros
Categories:
  - System
  - Shell
  - Network
  - RemoteAccess
Custom:
  Repo: https://github.com/mobile-shell/mosh
  PackagingRepo: https://github.com/sailfishos-chum/mosh
PackageIcon: https://raw.githubusercontent.com/mobile-shell/mobile-shell.github.io/master/mosh-chrome.png
Screenshots:
  - https://raw.githubusercontent.com/mobile-shell/mobile-shell.github.io/master/mosh.png
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%reconfigure --disable-static \
    --enable-client \
    --enable-server \
    --enable-completion

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# install a firewall rules file:
install -d %{buildroot}%{_sysconfdir}/connman/firewall.d/
install -m 644 %SOURCE1 %{buildroot}%{_sysconfdir}/connman/firewall.d/
# do not package documentation:
rm -rf %{buildroot}%{_docdir}
rm -rf %{buildroot}%{_mandir}
# fix perl shebang:
printf 'setting shebang for perl interpreter to #!%s\n' %{__perl}
find %{buildroot}/%{_bindir} -type f -exec sed -i '1s=^#!/usr/bin/\(perl\|env perl\)[5]\?=#!%{__perl}=' {} +

# << install post

%files
%defattr(-,root,root,-)
%license COPYING
%doc README.md
%{_bindir}/%{name}
%{_bindir}/%{name}-client
%config %{_sysconfdir}/bash_completion.d/%{name}*
# >> files
# << files

%files server
%defattr(-,root,root,-)
%{_bindir}/%{name}-server
%config(noreplace) %{_sysconfdir}/connman/firewall.d/99-mosh-firewall.conf
# >> files server
# << files server
